### ISSUE TITLE
Acknowledgement/Thank you

### ISSUE THREAD

**Issue by Michael-L-Miller** [BEFH/sinai_thesis#1]
Is there also a section to add a thank you statement (dedication or quote) prior to the acknowledgement?

**Comment by BEFH** [comment]
It's not a standard part of the Sinai thesis specification, but I can add
it...

**Comment by Michael-L-Miller** [comment]
Oh I see. I didn’t realize that.

How about abbreviations?

**Comment by BEFH** [comment]
You should be able to just make a section for that in the frontmatter using
a package. If you're at Sinai, or in the neighborhood, why don't you just
come on over and I can show you. Otherwise I can send you some example
source.

**Comment by Michael-L-Miller** [comment]
Sweet thanks

**Comment by BEFH** [comment]
Before the frontmatter:

```latex
\documentclass{sinai}
\usepackage{lipsum}

\usepackage[acronym]{glossaries}

% abbreviations:
\newacronym{ny}{NY}{New York}
\newacronym{la}{LA}{Los Angeles}
\newacronym{un}{UN}{United Nations}

% nomenclature:
\newglossaryentry{angelsperarea}{
  name = $a$ ,
  description = The number of angels per unit area,
}
\newglossaryentry{numofangels}{
  name = $N$ ,
  description = The number of angels per needle point
}
\newglossaryentry{areaofneedle}{
  name = $A$ ,
  description = The area of the needle point
}
\makeglossaries

...
```

In the frontmatter:
```latex
\begin{document}

\frontmatter

```
Right before your acknowledgements page, you can put an extra thankyou:

```latex
\unchapter{Extra Thanks}
Thanks Everyone!

\begin{thank}
\lipsum[3]
\end{thank}
```

Then you can put abbreviations and glossary after the TOC and figure list:

```latex
\singlespacing
\tableofcontents
\listoftables
\listoffigures

\printglossary[type=\acronymtype,title=Abbreviations]

\printglossary[title=Nomenclature]
```

Make sure you put the terms in the main body or they won't show up in the glossaries.

```latex
\gls{ny}, \gls{la} and \gls{un} are abbreviations whereas
\gls{angelsperarea}, \gls{numofangels} and \gls{areaofneedle} are part of the
nomenclature
```

See [This stackexchange page](https://tex.stackexchange.com/questions/86666/how-to-create-both-list-of-abbreviations-and-list-of-nomenclature-using-nomencl) for more info.

I've attached an MWE. Just rename it with a `.tex` extension to use it.
[MWE.txt](https://github.com/BEFH/sinai_thesis/files/1975754/MWE.txt)
